"""Knowledge-graph builder for the second brain.

The "knowledge graph" here is intentionally lightweight: a set of curated
markdown notes under brain/concepts/ that cross-reference each other with
Obsidian-style [[wikilinks]]. This module parses those links, builds the graph,
and regenerates two artifacts:

* brain/Maps/Home.md       — the human-readable map of content (index + mermaid)
* brain/graph.json         — machine-readable nodes + edges

This is deterministic — no LLM, no network. Run it whenever notes change
(scripts/build_brain.py, or the CI check). Fundamentals do NOT get re-researched
on a schedule; only this regeneration runs, and only when notes actually change.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import config

_WIKILINK = re.compile(r"\[\[([^\]]+)\]\]")
_TITLE = re.compile(r"^#\s+(.+)$", re.MULTILINE)
CONCEPTS_DIR = config.ROOT / "brain" / "concepts"
MAPS_DIR = config.ROOT / "brain" / "Maps"
GRAPH_PATH = config.ROOT / "brain" / "graph.json"


def _slug(name: str) -> str:
    return name.strip().lower().replace(" ", "-")


def parse_notes(concepts_dir: Path = CONCEPTS_DIR) -> dict:
    """Read every concept note into {slug: {title, path, links, summary}}."""
    notes: dict[str, dict] = {}
    for path in sorted(concepts_dir.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        title_match = _TITLE.search(text)
        title = title_match.group(1).strip() if title_match else path.stem
        links = sorted({_slug(m) for m in _WIKILINK.findall(text)})
        summary = _first_paragraph(text)
        notes[path.stem] = {
            "title": title,
            "path": path,
            "links": links,
            "summary": summary,
        }
    return notes


def _first_paragraph(text: str) -> str:
    body = _TITLE.sub("", text, count=1).strip()
    for block in body.split("\n\n"):
        block = block.strip()
        if block and not block.startswith(("#", ">", "-", "*", "|")):
            return _WIKILINK.sub(r"\1", block).replace("\n", " ").strip()
    return ""


def build_graph(notes: dict) -> dict:
    """Build a nodes+edges graph; edges only point to notes that exist."""
    nodes = [{"id": slug, "title": data["title"]} for slug, data in notes.items()]
    edges = []
    for slug, data in notes.items():
        for target in data["links"]:
            if target in notes:
                edges.append({"source": slug, "target": target})
    return {"nodes": nodes, "edges": edges}


def _mermaid(graph: dict) -> str:
    lines = ["```mermaid", "graph LR"]
    for node in graph["nodes"]:
        lines.append(f'  {node["id"].replace("-", "_")}["{node["title"]}"]')
    for edge in graph["edges"]:
        s = edge["source"].replace("-", "_")
        t = edge["target"].replace("-", "_")
        lines.append(f"  {s} --> {t}")
    lines.append("```")
    return "\n".join(lines)


def render_home(notes: dict, graph: dict) -> str:
    """Render brain/Maps/Home.md from the parsed notes and graph."""
    n_nodes = len(graph["nodes"])
    n_edges = len(graph["edges"])
    out = [
        "# Home — the-network second brain",
        "",
        "> Auto-generated by `src/brain.py` (`python scripts/build_brain.py`). "
        "Edit the notes under `brain/concepts/`, not this file.",
        "",
        f"**{n_nodes} concepts · {n_edges} links.** Curated, leak-free reference "
        "for the methods this repo actually uses. Fundamentals are written once "
        "and only updated when our methods change — they are not re-researched on "
        "a schedule.",
        "",
        "## Concept map",
        "",
        _mermaid(graph),
        "",
        "## Concepts",
        "",
    ]
    for slug in sorted(notes):
        data = notes[slug]
        rel = data["path"].relative_to(config.ROOT)
        out.append(f"- [{data['title']}]({Path('..') / 'concepts' / data['path'].name}) "
                   f"— {data['summary']}")
    out.append("")
    out.append("## Related")
    out.append("")
    out.append("- News intelligence log: `brain/news/` (per-ticker, point-in-time).")
    out.append("- Methodology lives in code: `src/features.py`, `src/backtest.py`.")
    out.append("")
    return "\n".join(out)


def rebuild(concepts_dir: Path = CONCEPTS_DIR) -> dict:
    """Parse notes, build the graph, and write Home.md + graph.json."""
    notes = parse_notes(concepts_dir)
    graph = build_graph(notes)
    MAPS_DIR.mkdir(parents=True, exist_ok=True)
    (MAPS_DIR / "Home.md").write_text(render_home(notes, graph), encoding="utf-8")
    GRAPH_PATH.write_text(json.dumps(graph, indent=2), encoding="utf-8")
    return graph
